Trainee dashboards
PolusAI/examples pull request #15
Opened 2023-06-12 19:24 UTC by aditipate

**This PR adds the following dashboards:**

- **Dash Manhattan Plot dashboard**
This dashboard utilizes the Plotly Dash Bio Suite to present an interactive Manhattan plot, allowing users to explore GWAS data. It includes a slider to modify the Genome Wide Significance threshold and a Dash table to display top SNPs and their associated gene/gene summaries.

- **Streamlit Stroke Predictor dashboard**
This dashboard includes a stroke predictor form containing fields for determinants of stroke. A user can provide this data for a hypothetical individual, which are then used by a classifier to predict the likelihood of the individual experiencing stroke.

- **Streamlit Image Comparison dashboard**
This dashboard allows users to select a pair of images consisting of a raw and flat field corrected image. Images are displayed side by side using the Streamlit Image Comparison component so that they may be compared by adjusting a slider, overall enhancing the ability to visualize differences.

- PR also includes READMEs for each of the dashboards. 
- Sample data needs to be added to Streamlit Image Comparison dashboard

2023-06-28 16:05 UTC, ktaletsk commented on tutorials/dash/dash-manhattan-plot/app.py
> +    Entrez.email = " please provide your email here "
Use `JUPYTERHUB_USER` env variable. It is going to contain user's

2023-06-29 21:35 UTC, aditipate commented on tutorials/dash/dash-manhattan-plot/app.py
> +    Entrez.email = " please provide your email here "
**Branch updates:**

* Updated Dash example to use `JUPYTER_USER` env variable to retrieve user's email
* Also updated README to remove email instructions

2023-06-29 22:34 UTC, aditipate commented
**Additional update:**

- Added verification and validation for user email

2023-06-30 03:20 UTC, ktaletsk requested changes

2023-06-30 03:20 UTC, ktaletsk commented on tutorials/dash/dash-manhattan-plot/app.py
> +import re
Built-in dependencies are imported in the top

2023-06-30 03:20 UTC, ktaletsk commented on tutorials/dash/dash-manhattan-plot/app.py
> +    Entrez.email = entrez_email
You can save one variable allocation and combine these two lines in one

2023-06-30 15:15 UTC, aditipate commented on tutorials/dash/dash-manhattan-plot/app.py
> +    Entrez.email = entrez_email
Got it! Just updated and combined the lines

2023-06-30 20:03 UTC, ktaletsk approved these changes
Congratulations on your first PR merged into PolusAI!

2023-06-30 20:03 UTC, merged