Plotly Dash - Dash Bio Examples
PolusAI/examples pull request #19
Opened 2023-09-08 19:06 UTC by aditipate

This Pr:

Adds examples from the Dash Bio suite - a suite of bioinformatics components that make it simpler to analyze and visualize bioinformatics data and interact with them in a Dash application.
There are 16 total examples that utilize data/components in categories ranging from molecular, genomic, and chromosome data.
Examples were tested locally and in the Trainee cluster.

2023-10-31 00:57 UTC, ktaletsk requested changes
Everyhting mostly looks good. I was able to launch all of the examples in Notebooks Hub.

Main request here is to download the data from server, check in the data into this folder with Dash examples and load it locally

See my comments for the full list of requests

2023-10-31 00:57 UTC, ktaletsk commented on tutorials/dash/dash-bio-suite/06-alignmentchart.py
Output looks like raw HTML (not rendered). Do you see the same when you start this dashboard?
<img width="2510" alt="image" src="https://github.com/PolusAI/examples/assets/8834829/5cb42b00-758c-4d28-a26c-9cb69c110333">

2023-10-31 00:57 UTC, ktaletsk commented on tutorials/dash/dash-bio-suite/16-manhattanplot.py
I am confused. What is the difference between this example and Manhattan plot you have previously created at `tutorials/dash/dash-manhattan-plot/app.py`?

2023-10-31 16:45 UTC, aditipate commented on tutorials/dash/dash-bio-suite/01-molecule2dviewer.py
> +).read().decode('utf-8')
That's a good suggestion. I added all of the data being used in the dash-bio-suite examples and added them to tutorials/dash/dash-bio-suite/data.

2023-10-31 16:46 UTC, aditipate commented on tutorials/dash/dash-bio-suite/06-alignmentchart.py
Yes, I'm also getting the same output when I run the dashboard. Just re-ran locally.

2023-10-31 16:46 UTC, aditipate commented on tutorials/dash/dash-bio-suite/16-manhattanplot.py
Both examples include the dash manhattan plot + slider and utilize the same data, however my example has an additional component which is the gene summary table. Significant SNP data is passed to the the gene summary table, along with additional info about the significant genes that's been queried from NCBI (e.g summaries).

2023-10-31 17:50 UTC, ktaletsk commented on tutorials/dash/dash-bio-suite/16-manhattanplot.py
Ok, if it's the same plot type with the same data, let's replace this example with your example

2023-10-31 17:51 UTC, ktaletsk commented on tutorials/dash/dash-bio-suite/06-alignmentchart.py
Could you come up with a fix, so it does not show the raw HTML, but rendered instead?

2023-11-01 16:36 UTC, ktaletsk approved these changes

2023-11-01 16:36 UTC, merged